#Uncomment the volumes mount for live coding
version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./vhosts/default.conf:/etc/nginx/conf.d/default.conf
      #- ./certs/:/etc/nginx/ssl/
    depends_on:
      - live
    ports:
      - "8088:80"
  live:
    image: dynedjakartacontainers/live:1.0.0
    ports:
      - "80:80"
    tty: true
    #command: start.sh
    depends_on:
      - beanstalkd
    volumes:
      - ./live/.:/var/www/html/
    env_file: .env
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
